### ISSUE TITLE
Add CMake flag that disables building tests.

### ISSUE THREAD

**Issue by matoushybl** [Robotics-BUT/Robotic-Template-Library#1]
Building tests takes a lot of resources and time on embedded platforms, it would be nice to be able to disable test building.

**Comment by adamek727** [comment]
will be added in upcoming release

**Comment by AlesJelinek** [comment]
Fixed in recent release of RTL - it is now header-only and compilation of tests and examples is controlled via command-line options. Please see Cmake files for details.
